package com.telecomjs.mappers;

import com.telecomjs.beans.AppYdbpAreaChannel;

public interface AppYdbpAreaChannelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_YDBP_AREA_CHANNEL
     *
     * @mbggenerated
     */
    int insert(AppYdbpAreaChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_YDBP_AREA_CHANNEL
     *
     * @mbggenerated
     */
    int insertSelective(AppYdbpAreaChannel record);
}