package com.telecomjs.mappers;

import com.telecomjs.beans.AppYdbpArea;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface AppYdbpAreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_YDBP_AREA
     *
     * @mbggenerated
     */
    int insert(AppYdbpArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_YDBP_AREA
     *
     * @mbggenerated
     */
    int insertSelective(AppYdbpArea record);

    List<AppYdbpArea> findAll();


    List<Map> findL2ByArea(@Param("areaId") long areaId);

    List<AppYdbpArea> findAllAreas();
}