package com.telecomjs.mappers;

import com.telecomjs.beans.AssessmentEvent;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

public interface AssessmentEventMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ASSESSMENT_EVENT
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer eventId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ASSESSMENT_EVENT
     *
     * @mbggenerated
     */
    int insert(AssessmentEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ASSESSMENT_EVENT
     *
     * @mbggenerated
     */
    int insertSelective(AssessmentEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ASSESSMENT_EVENT
     *
     * @mbggenerated
     */
    AssessmentEvent selectByPrimaryKey(Integer eventId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ASSESSMENT_EVENT
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AssessmentEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ASSESSMENT_EVENT
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AssessmentEvent record);

    int getPrimaryKey();

    List<AssessmentEvent> findAll();

    int closeEvent(@Param("eventId") int eventId);

    int reportEvent(@Param("eventId") int eventId);

    int countEventsByCycle(@Param("billingCycleId") int billingCycleId);
}