package com.telecomjs.mappers;

import com.telecomjs.beans.AssessmentLog;

public interface AssessmentLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ASSESSMENT_LOG
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ASSESSMENT_LOG
     *
     * @mbggenerated
     */
    int insert(AssessmentLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ASSESSMENT_LOG
     *
     * @mbggenerated
     */
    int insertSelective(AssessmentLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ASSESSMENT_LOG
     *
     * @mbggenerated
     */
    AssessmentLog selectByPrimaryKey(Integer logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ASSESSMENT_LOG
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AssessmentLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ASSESSMENT_LOG
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AssessmentLog record);

    Integer getPrimaryKey();
}