package com.telecomjs.mappers;

import com.telecomjs.beans.AssessmentSignature;
import org.apache.ibatis.annotations.Param;

public interface AssessmentSignatureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ASSESSMENT_SIGNATURE
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer signatureId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ASSESSMENT_SIGNATURE
     *
     * @mbggenerated
     */
    int insert(AssessmentSignature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ASSESSMENT_SIGNATURE
     *
     * @mbggenerated
     */
    int insertSelective(AssessmentSignature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ASSESSMENT_SIGNATURE
     *
     * @mbggenerated
     */
    AssessmentSignature selectByPrimaryKey(Integer signatureId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ASSESSMENT_SIGNATURE
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AssessmentSignature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ASSESSMENT_SIGNATURE
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(AssessmentSignature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ASSESSMENT_SIGNATURE
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AssessmentSignature record);

    Integer getPrimaryKey();

    int endSignature(@Param("assessmentId") Integer assessmentId);
    int updateSignatureWithState(@Param("assessmentId") Integer assessmentId, @Param("state") String state);

    AssessmentSignature findSignature(@Param("assessmentId") int assessmentId);
    int existsSignature(@Param("assessmentId") int assessmentId);
}