package com.telecomjs.mappers;

import com.telecomjs.beans.BillingCycle;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BillingCycleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BILLING_CYCLE
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer billingCycleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BILLING_CYCLE
     *
     * @mbggenerated
     */
    int insert(BillingCycle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BILLING_CYCLE
     *
     * @mbggenerated
     */
    int insertSelective(BillingCycle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BILLING_CYCLE
     *
     * @mbggenerated
     */
    BillingCycle selectByPrimaryKey(Integer billingCycleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BILLING_CYCLE
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BillingCycle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BILLING_CYCLE
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BillingCycle record);

    String getState(@Param("billingCycleId") int billingCycleId);
    int changeState(@Param("billingCycle") int billingCycle , @Param("state") String state);

    List<BillingCycle> findAll();

    List<BillingCycle> findAllCycles();
}