package com.telecomjs.mappers;

import com.telecomjs.beans.ItemCategory;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ItemCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ITEM_CATEGORY
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Short categoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ITEM_CATEGORY
     *
     * @mbggenerated
     */
    int insert(ItemCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ITEM_CATEGORY
     *
     * @mbggenerated
     */
    int insertSelective(ItemCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ITEM_CATEGORY
     *
     * @mbggenerated
     */
    ItemCategory selectByPrimaryKey(Short categoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ITEM_CATEGORY
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ItemCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ITEM_CATEGORY
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ItemCategory record);

    int getPrimaryKey();

    List<ItemCategory> findAll();

    List<ItemCategory> findAllCategoriesByRole(@Param("name") String name);
}