package com.telecomjs.mappers;

import com.telecomjs.beans.StaffAssessment;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface StaffAssessmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAFF_ASSESSMENT
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAFF_ASSESSMENT
     *
     * @mbggenerated
     */
    int insert(StaffAssessment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAFF_ASSESSMENT
     *
     * @mbggenerated
     */
    int insertSelective(StaffAssessment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAFF_ASSESSMENT
     *
     * @mbggenerated
     */
    StaffAssessment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAFF_ASSESSMENT
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StaffAssessment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAFF_ASSESSMENT
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StaffAssessment record);

    int getPrimaryKey();

    List<StaffAssessment> findAssessmentById(@Param("assessmentId") int assessmentId);

    List<StaffAssessment> findAssessmentByZone(@Param("zoneId") long zoneId);

    int auditAssessmentWithState(@Param("assessmentId") int assessmentId, @Param("state") String state);
}