package com.telecomjs.mappers;

import com.telecomjs.beans.StaffAssessmentItem;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface StaffAssessmentItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAFF_ASSESSMENT_ITEM
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAFF_ASSESSMENT_ITEM
     *
     * @mbggenerated
     */
    int insert(StaffAssessmentItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAFF_ASSESSMENT_ITEM
     *
     * @mbggenerated
     */
    int insertSelective(StaffAssessmentItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAFF_ASSESSMENT_ITEM
     *
     * @mbggenerated
     */
    StaffAssessmentItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAFF_ASSESSMENT_ITEM
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StaffAssessmentItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAFF_ASSESSMENT_ITEM
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StaffAssessmentItem record);

    void deleteByStaffAssessmentId(@Param("staffAssessmentId") Integer staffAssessmentId);

    Integer getPrimaryKey();

    List<StaffAssessmentItem> findItemsByStaffAssessmentId(@Param("staffAssessmentId") int staffAssessmentId);
}