package com.telecomjs.mappers;

import com.telecomjs.beans.ZoneMarkAssessment;

public interface ZoneMarkAssessmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZONE_MARK_ASSESSMENT
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long markId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZONE_MARK_ASSESSMENT
     *
     * @mbggenerated
     */
    int insert(ZoneMarkAssessment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZONE_MARK_ASSESSMENT
     *
     * @mbggenerated
     */
    int insertSelective(ZoneMarkAssessment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZONE_MARK_ASSESSMENT
     *
     * @mbggenerated
     */
    ZoneMarkAssessment selectByPrimaryKey(Long markId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZONE_MARK_ASSESSMENT
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ZoneMarkAssessment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZONE_MARK_ASSESSMENT
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ZoneMarkAssessment record);
}