package com.telecomjs.mappers;

import com.telecomjs.beans.ZoneMark;
import com.telecomjs.beans.ZoneMarkWithItem;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ZoneMarkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZONE_MARK
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long markId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZONE_MARK
     *
     * @mbggenerated
     */
    int insert(ZoneMark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZONE_MARK
     *
     * @mbggenerated
     */
    int insertSelective(ZoneMark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZONE_MARK
     *
     * @mbggenerated
     */
    ZoneMark selectByPrimaryKey(Long markId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZONE_MARK
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ZoneMark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZONE_MARK
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ZoneMark record);

    ZoneMarkWithItem findMarkWithCode(@Param("zoneId") long zoneId, @Param("billingCycle") int billingCycle, @Param("code") String code);

    List<ZoneMark> findMDCN(@Param("billingCycle") int billingCycle);
    List<ZoneMark> findSTLTS(@Param("billingCycle") int billingCycle);
    List<ZoneMark> findZWYX(@Param("billingCycle") int billingCycle);
    //删除账期内容
    int deleteByCycle(@Param("billingCycle") int billingCycle);

    Long getPrimaryKey();

    int insertManual(@Param("billingCycle") int billingCycle);

    int insertBatch(@Param("markList") List<ZoneMark> markList);
}