package com.telecomjs.mappers;

import com.telecomjs.beans.ZoneMark;

public interface ZoneMarkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZONE_MARK
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long markId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZONE_MARK
     *
     * @mbggenerated
     */
    int insert(ZoneMark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZONE_MARK
     *
     * @mbggenerated
     */
    int insertSelective(ZoneMark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZONE_MARK
     *
     * @mbggenerated
     */
    ZoneMark selectByPrimaryKey(Long markId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZONE_MARK
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ZoneMark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZONE_MARK
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ZoneMark record);
}