package com.telecomjs.mappers;

import com.telecomjs.beans.ZoneMarkItem;
import org.apache.ibatis.annotations.Param;

public interface ZoneMarkItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZONE_MARK_ITEM
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZONE_MARK_ITEM
     *
     * @mbggenerated
     */
    int insert(ZoneMarkItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZONE_MARK_ITEM
     *
     * @mbggenerated
     */
    int insertSelective(ZoneMarkItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZONE_MARK_ITEM
     *
     * @mbggenerated
     */
    ZoneMarkItem selectByPrimaryKey(Long itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZONE_MARK_ITEM
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ZoneMarkItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZONE_MARK_ITEM
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ZoneMarkItem record);

    long getIdByCode(@Param("code") String code);
    ZoneMarkItem getByCode(@Param("code") String code);
}