package com.telecomjs.mappers;

import com.telecomjs.beans.ZoneMarkEvent;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ZoneMarkEventMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZONE_MARK_EVENT
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long eventId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZONE_MARK_EVENT
     *
     * @mbggenerated
     */
    int insert(ZoneMarkEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZONE_MARK_EVENT
     *
     * @mbggenerated
     */
    int insertSelective(ZoneMarkEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZONE_MARK_EVENT
     *
     * @mbggenerated
     */
    ZoneMarkEvent selectByPrimaryKey(Long eventId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZONE_MARK_EVENT
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ZoneMarkEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZONE_MARK_EVENT
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ZoneMarkEvent record);

    long getPrimaryKey();

    List<ZoneMarkEvent> findEventsByCycle(@Param("billingCycle") int billingCycle);

    List<ZoneMarkEvent> findAll();

    int updateState(@Param("eventId") int eventId, @Param("name") String name);
}