package com.telecomjs.beans;

public class AppYdbpAreaChannel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_YDBP_AREA_CHANNEL.DISP_SEQ
     *
     * @mbggenerated
     */
    private Short dispSeq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_YDBP_AREA_CHANNEL.AREA_ID
     *
     * @mbggenerated
     */
    private Short areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_YDBP_AREA_CHANNEL.AREA_NAME
     *
     * @mbggenerated
     */
    private String areaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_YDBP_AREA_CHANNEL.AREA_ID_L2
     *
     * @mbggenerated
     */
    private Long areaIdL2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_YDBP_AREA_CHANNEL.AREA_NAME_L2
     *
     * @mbggenerated
     */
    private String areaNameL2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_YDBP_AREA_CHANNEL.AREA_NAME_TM
     *
     * @mbggenerated
     */
    private String areaNameTm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_YDBP_AREA_CHANNEL.AREA_ID_TM
     *
     * @mbggenerated
     */
    private Long areaIdTm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_YDBP_AREA_CHANNEL.BSS_CHANNEL_ID
     *
     * @mbggenerated
     */
    private Long bssChannelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_YDBP_AREA_CHANNEL.CHANNEL_NAME
     *
     * @mbggenerated
     */
    private String channelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_YDBP_AREA_CHANNEL.CHANNEL_ID
     *
     * @mbggenerated
     */
    private Long channelId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_YDBP_AREA_CHANNEL.DISP_SEQ
     *
     * @return the value of APP_YDBP_AREA_CHANNEL.DISP_SEQ
     *
     * @mbggenerated
     */
    public Short getDispSeq() {
        return dispSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_YDBP_AREA_CHANNEL.DISP_SEQ
     *
     * @param dispSeq the value for APP_YDBP_AREA_CHANNEL.DISP_SEQ
     *
     * @mbggenerated
     */
    public void setDispSeq(Short dispSeq) {
        this.dispSeq = dispSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_YDBP_AREA_CHANNEL.AREA_ID
     *
     * @return the value of APP_YDBP_AREA_CHANNEL.AREA_ID
     *
     * @mbggenerated
     */
    public Short getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_YDBP_AREA_CHANNEL.AREA_ID
     *
     * @param areaId the value for APP_YDBP_AREA_CHANNEL.AREA_ID
     *
     * @mbggenerated
     */
    public void setAreaId(Short areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_YDBP_AREA_CHANNEL.AREA_NAME
     *
     * @return the value of APP_YDBP_AREA_CHANNEL.AREA_NAME
     *
     * @mbggenerated
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_YDBP_AREA_CHANNEL.AREA_NAME
     *
     * @param areaName the value for APP_YDBP_AREA_CHANNEL.AREA_NAME
     *
     * @mbggenerated
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName == null ? null : areaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_YDBP_AREA_CHANNEL.AREA_ID_L2
     *
     * @return the value of APP_YDBP_AREA_CHANNEL.AREA_ID_L2
     *
     * @mbggenerated
     */
    public Long getAreaIdL2() {
        return areaIdL2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_YDBP_AREA_CHANNEL.AREA_ID_L2
     *
     * @param areaIdL2 the value for APP_YDBP_AREA_CHANNEL.AREA_ID_L2
     *
     * @mbggenerated
     */
    public void setAreaIdL2(Long areaIdL2) {
        this.areaIdL2 = areaIdL2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_YDBP_AREA_CHANNEL.AREA_NAME_L2
     *
     * @return the value of APP_YDBP_AREA_CHANNEL.AREA_NAME_L2
     *
     * @mbggenerated
     */
    public String getAreaNameL2() {
        return areaNameL2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_YDBP_AREA_CHANNEL.AREA_NAME_L2
     *
     * @param areaNameL2 the value for APP_YDBP_AREA_CHANNEL.AREA_NAME_L2
     *
     * @mbggenerated
     */
    public void setAreaNameL2(String areaNameL2) {
        this.areaNameL2 = areaNameL2 == null ? null : areaNameL2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_YDBP_AREA_CHANNEL.AREA_NAME_TM
     *
     * @return the value of APP_YDBP_AREA_CHANNEL.AREA_NAME_TM
     *
     * @mbggenerated
     */
    public String getAreaNameTm() {
        return areaNameTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_YDBP_AREA_CHANNEL.AREA_NAME_TM
     *
     * @param areaNameTm the value for APP_YDBP_AREA_CHANNEL.AREA_NAME_TM
     *
     * @mbggenerated
     */
    public void setAreaNameTm(String areaNameTm) {
        this.areaNameTm = areaNameTm == null ? null : areaNameTm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_YDBP_AREA_CHANNEL.AREA_ID_TM
     *
     * @return the value of APP_YDBP_AREA_CHANNEL.AREA_ID_TM
     *
     * @mbggenerated
     */
    public Long getAreaIdTm() {
        return areaIdTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_YDBP_AREA_CHANNEL.AREA_ID_TM
     *
     * @param areaIdTm the value for APP_YDBP_AREA_CHANNEL.AREA_ID_TM
     *
     * @mbggenerated
     */
    public void setAreaIdTm(Long areaIdTm) {
        this.areaIdTm = areaIdTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_YDBP_AREA_CHANNEL.BSS_CHANNEL_ID
     *
     * @return the value of APP_YDBP_AREA_CHANNEL.BSS_CHANNEL_ID
     *
     * @mbggenerated
     */
    public Long getBssChannelId() {
        return bssChannelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_YDBP_AREA_CHANNEL.BSS_CHANNEL_ID
     *
     * @param bssChannelId the value for APP_YDBP_AREA_CHANNEL.BSS_CHANNEL_ID
     *
     * @mbggenerated
     */
    public void setBssChannelId(Long bssChannelId) {
        this.bssChannelId = bssChannelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_YDBP_AREA_CHANNEL.CHANNEL_NAME
     *
     * @return the value of APP_YDBP_AREA_CHANNEL.CHANNEL_NAME
     *
     * @mbggenerated
     */
    public String getChannelName() {
        return channelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_YDBP_AREA_CHANNEL.CHANNEL_NAME
     *
     * @param channelName the value for APP_YDBP_AREA_CHANNEL.CHANNEL_NAME
     *
     * @mbggenerated
     */
    public void setChannelName(String channelName) {
        this.channelName = channelName == null ? null : channelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_YDBP_AREA_CHANNEL.CHANNEL_ID
     *
     * @return the value of APP_YDBP_AREA_CHANNEL.CHANNEL_ID
     *
     * @mbggenerated
     */
    public Long getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_YDBP_AREA_CHANNEL.CHANNEL_ID
     *
     * @param channelId the value for APP_YDBP_AREA_CHANNEL.CHANNEL_ID
     *
     * @mbggenerated
     */
    public void setChannelId(Long channelId) {
        this.channelId = channelId;
    }
}