package com.telecomjs.beans;

public class AppYdbpAreaZwstaff {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_YDBP_AREA_ZWSTAFF.DISP_SEQ
     *
     * @mbggenerated
     */
    private Short dispSeq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_YDBP_AREA_ZWSTAFF.AREA_ID
     *
     * @mbggenerated
     */
    private Long areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_YDBP_AREA_ZWSTAFF.AREA_NAME
     *
     * @mbggenerated
     */
    private String areaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_YDBP_AREA_ZWSTAFF.AREA_ID_L2
     *
     * @mbggenerated
     */
    private Long areaIdL2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_YDBP_AREA_ZWSTAFF.AREA_NAME_L2
     *
     * @mbggenerated
     */
    private String areaNameL2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_YDBP_AREA_ZWSTAFF.AREA_NAME_TM
     *
     * @mbggenerated
     */
    private String areaNameTm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_YDBP_AREA_ZWSTAFF.AREA_ID_TM
     *
     * @mbggenerated
     */
    private Long areaIdTm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_YDBP_AREA_ZWSTAFF.ASSIST_NUM
     *
     * @mbggenerated
     */
    private String assistNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_YDBP_AREA_ZWSTAFF.STAFF_NAME
     *
     * @mbggenerated
     */
    private String staffName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_YDBP_AREA_ZWSTAFF.DISP_SEQ
     *
     * @return the value of APP_YDBP_AREA_ZWSTAFF.DISP_SEQ
     *
     * @mbggenerated
     */
    public Short getDispSeq() {
        return dispSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_YDBP_AREA_ZWSTAFF.DISP_SEQ
     *
     * @param dispSeq the value for APP_YDBP_AREA_ZWSTAFF.DISP_SEQ
     *
     * @mbggenerated
     */
    public void setDispSeq(Short dispSeq) {
        this.dispSeq = dispSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_YDBP_AREA_ZWSTAFF.AREA_ID
     *
     * @return the value of APP_YDBP_AREA_ZWSTAFF.AREA_ID
     *
     * @mbggenerated
     */
    public Long getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_YDBP_AREA_ZWSTAFF.AREA_ID
     *
     * @param areaId the value for APP_YDBP_AREA_ZWSTAFF.AREA_ID
     *
     * @mbggenerated
     */
    public void setAreaId(Long areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_YDBP_AREA_ZWSTAFF.AREA_NAME
     *
     * @return the value of APP_YDBP_AREA_ZWSTAFF.AREA_NAME
     *
     * @mbggenerated
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_YDBP_AREA_ZWSTAFF.AREA_NAME
     *
     * @param areaName the value for APP_YDBP_AREA_ZWSTAFF.AREA_NAME
     *
     * @mbggenerated
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName == null ? null : areaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_YDBP_AREA_ZWSTAFF.AREA_ID_L2
     *
     * @return the value of APP_YDBP_AREA_ZWSTAFF.AREA_ID_L2
     *
     * @mbggenerated
     */
    public Long getAreaIdL2() {
        return areaIdL2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_YDBP_AREA_ZWSTAFF.AREA_ID_L2
     *
     * @param areaIdL2 the value for APP_YDBP_AREA_ZWSTAFF.AREA_ID_L2
     *
     * @mbggenerated
     */
    public void setAreaIdL2(Long areaIdL2) {
        this.areaIdL2 = areaIdL2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_YDBP_AREA_ZWSTAFF.AREA_NAME_L2
     *
     * @return the value of APP_YDBP_AREA_ZWSTAFF.AREA_NAME_L2
     *
     * @mbggenerated
     */
    public String getAreaNameL2() {
        return areaNameL2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_YDBP_AREA_ZWSTAFF.AREA_NAME_L2
     *
     * @param areaNameL2 the value for APP_YDBP_AREA_ZWSTAFF.AREA_NAME_L2
     *
     * @mbggenerated
     */
    public void setAreaNameL2(String areaNameL2) {
        this.areaNameL2 = areaNameL2 == null ? null : areaNameL2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_YDBP_AREA_ZWSTAFF.AREA_NAME_TM
     *
     * @return the value of APP_YDBP_AREA_ZWSTAFF.AREA_NAME_TM
     *
     * @mbggenerated
     */
    public String getAreaNameTm() {
        return areaNameTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_YDBP_AREA_ZWSTAFF.AREA_NAME_TM
     *
     * @param areaNameTm the value for APP_YDBP_AREA_ZWSTAFF.AREA_NAME_TM
     *
     * @mbggenerated
     */
    public void setAreaNameTm(String areaNameTm) {
        this.areaNameTm = areaNameTm == null ? null : areaNameTm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_YDBP_AREA_ZWSTAFF.AREA_ID_TM
     *
     * @return the value of APP_YDBP_AREA_ZWSTAFF.AREA_ID_TM
     *
     * @mbggenerated
     */
    public Long getAreaIdTm() {
        return areaIdTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_YDBP_AREA_ZWSTAFF.AREA_ID_TM
     *
     * @param areaIdTm the value for APP_YDBP_AREA_ZWSTAFF.AREA_ID_TM
     *
     * @mbggenerated
     */
    public void setAreaIdTm(Long areaIdTm) {
        this.areaIdTm = areaIdTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_YDBP_AREA_ZWSTAFF.ASSIST_NUM
     *
     * @return the value of APP_YDBP_AREA_ZWSTAFF.ASSIST_NUM
     *
     * @mbggenerated
     */
    public String getAssistNum() {
        return assistNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_YDBP_AREA_ZWSTAFF.ASSIST_NUM
     *
     * @param assistNum the value for APP_YDBP_AREA_ZWSTAFF.ASSIST_NUM
     *
     * @mbggenerated
     */
    public void setAssistNum(String assistNum) {
        this.assistNum = assistNum == null ? null : assistNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_YDBP_AREA_ZWSTAFF.STAFF_NAME
     *
     * @return the value of APP_YDBP_AREA_ZWSTAFF.STAFF_NAME
     *
     * @mbggenerated
     */
    public String getStaffName() {
        return staffName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_YDBP_AREA_ZWSTAFF.STAFF_NAME
     *
     * @param staffName the value for APP_YDBP_AREA_ZWSTAFF.STAFF_NAME
     *
     * @mbggenerated
     */
    public void setStaffName(String staffName) {
        this.staffName = staffName == null ? null : staffName.trim();
    }
}