package com.telecomjs.beans;

import java.math.BigDecimal;
import java.util.Date;

public class Assessment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSESSMENT.ASSESSMENT_ID
     *
     * @mbggenerated
     */
    private Integer assessmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSESSMENT.ASSESSMENT_EVENT_ID
     *
     * @mbggenerated
     */
    private Integer assessmentEventId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSESSMENT.AREA_NAME
     *
     * @mbggenerated
     */
    private String areaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSESSMENT.DISTRICT_NAME
     *
     * @mbggenerated
     */
    private String districtName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSESSMENT.ZONE_NAME
     *
     * @mbggenerated
     */
    private String zoneName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSESSMENT.ZONE_ATTR
     *
     * @mbggenerated
     */
    private String zoneAttr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSESSMENT.ZONE_CHANNEL_CODE
     *
     * @mbggenerated
     */
    private Long zoneChannelCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSESSMENT.CHANNEL_NAME
     *
     * @mbggenerated
     */
    private String channelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSESSMENT.ZONE_ID
     *
     * @mbggenerated
     */
    private Long zoneId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSESSMENT.BILLING_CYCLE
     *
     * @mbggenerated
     */
    private Integer billingCycle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSESSMENT.SCORE
     *
     * @mbggenerated
     */
    private BigDecimal score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSESSMENT.CRITERION
     *
     * @mbggenerated
     */
    private BigDecimal criterion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSESSMENT.LAST_REWARD
     *
     * @mbggenerated
     */
    private BigDecimal lastReward;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSESSMENT.LAST_FORWARD_REWARD
     *
     * @mbggenerated
     */
    private BigDecimal lastForwardReward;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSESSMENT.LAST_SETTLEMENT
     *
     * @mbggenerated
     */
    private BigDecimal lastSettlement;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSESSMENT.FORWARD_REWARD
     *
     * @mbggenerated
     */
    private BigDecimal forwardReward;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSESSMENT.REWARD
     *
     * @mbggenerated
     */
    private BigDecimal reward;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSESSMENT.DOUBLE_REWARD
     *
     * @mbggenerated
     */
    private BigDecimal doubleReward;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSESSMENT.STATE
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSESSMENT.CREATE_DATE
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSESSMENT.ASSESSMENT_ID
     *
     * @return the value of ASSESSMENT.ASSESSMENT_ID
     *
     * @mbggenerated
     */
    public Integer getAssessmentId() {
        return assessmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSESSMENT.ASSESSMENT_ID
     *
     * @param assessmentId the value for ASSESSMENT.ASSESSMENT_ID
     *
     * @mbggenerated
     */
    public void setAssessmentId(Integer assessmentId) {
        this.assessmentId = assessmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSESSMENT.ASSESSMENT_EVENT_ID
     *
     * @return the value of ASSESSMENT.ASSESSMENT_EVENT_ID
     *
     * @mbggenerated
     */
    public Integer getAssessmentEventId() {
        return assessmentEventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSESSMENT.ASSESSMENT_EVENT_ID
     *
     * @param assessmentEventId the value for ASSESSMENT.ASSESSMENT_EVENT_ID
     *
     * @mbggenerated
     */
    public void setAssessmentEventId(Integer assessmentEventId) {
        this.assessmentEventId = assessmentEventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSESSMENT.AREA_NAME
     *
     * @return the value of ASSESSMENT.AREA_NAME
     *
     * @mbggenerated
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSESSMENT.AREA_NAME
     *
     * @param areaName the value for ASSESSMENT.AREA_NAME
     *
     * @mbggenerated
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName == null ? null : areaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSESSMENT.DISTRICT_NAME
     *
     * @return the value of ASSESSMENT.DISTRICT_NAME
     *
     * @mbggenerated
     */
    public String getDistrictName() {
        return districtName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSESSMENT.DISTRICT_NAME
     *
     * @param districtName the value for ASSESSMENT.DISTRICT_NAME
     *
     * @mbggenerated
     */
    public void setDistrictName(String districtName) {
        this.districtName = districtName == null ? null : districtName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSESSMENT.ZONE_NAME
     *
     * @return the value of ASSESSMENT.ZONE_NAME
     *
     * @mbggenerated
     */
    public String getZoneName() {
        return zoneName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSESSMENT.ZONE_NAME
     *
     * @param zoneName the value for ASSESSMENT.ZONE_NAME
     *
     * @mbggenerated
     */
    public void setZoneName(String zoneName) {
        this.zoneName = zoneName == null ? null : zoneName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSESSMENT.ZONE_ATTR
     *
     * @return the value of ASSESSMENT.ZONE_ATTR
     *
     * @mbggenerated
     */
    public String getZoneAttr() {
        return zoneAttr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSESSMENT.ZONE_ATTR
     *
     * @param zoneAttr the value for ASSESSMENT.ZONE_ATTR
     *
     * @mbggenerated
     */
    public void setZoneAttr(String zoneAttr) {
        this.zoneAttr = zoneAttr == null ? null : zoneAttr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSESSMENT.ZONE_CHANNEL_CODE
     *
     * @return the value of ASSESSMENT.ZONE_CHANNEL_CODE
     *
     * @mbggenerated
     */
    public Long getZoneChannelCode() {
        return zoneChannelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSESSMENT.ZONE_CHANNEL_CODE
     *
     * @param zoneChannelCode the value for ASSESSMENT.ZONE_CHANNEL_CODE
     *
     * @mbggenerated
     */
    public void setZoneChannelCode(Long zoneChannelCode) {
        this.zoneChannelCode = zoneChannelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSESSMENT.CHANNEL_NAME
     *
     * @return the value of ASSESSMENT.CHANNEL_NAME
     *
     * @mbggenerated
     */
    public String getChannelName() {
        return channelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSESSMENT.CHANNEL_NAME
     *
     * @param channelName the value for ASSESSMENT.CHANNEL_NAME
     *
     * @mbggenerated
     */
    public void setChannelName(String channelName) {
        this.channelName = channelName == null ? null : channelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSESSMENT.ZONE_ID
     *
     * @return the value of ASSESSMENT.ZONE_ID
     *
     * @mbggenerated
     */
    public Long getZoneId() {
        return zoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSESSMENT.ZONE_ID
     *
     * @param zoneId the value for ASSESSMENT.ZONE_ID
     *
     * @mbggenerated
     */
    public void setZoneId(Long zoneId) {
        this.zoneId = zoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSESSMENT.BILLING_CYCLE
     *
     * @return the value of ASSESSMENT.BILLING_CYCLE
     *
     * @mbggenerated
     */
    public Integer getBillingCycle() {
        return billingCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSESSMENT.BILLING_CYCLE
     *
     * @param billingCycle the value for ASSESSMENT.BILLING_CYCLE
     *
     * @mbggenerated
     */
    public void setBillingCycle(Integer billingCycle) {
        this.billingCycle = billingCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSESSMENT.SCORE
     *
     * @return the value of ASSESSMENT.SCORE
     *
     * @mbggenerated
     */
    public BigDecimal getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSESSMENT.SCORE
     *
     * @param score the value for ASSESSMENT.SCORE
     *
     * @mbggenerated
     */
    public void setScore(BigDecimal score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSESSMENT.CRITERION
     *
     * @return the value of ASSESSMENT.CRITERION
     *
     * @mbggenerated
     */
    public BigDecimal getCriterion() {
        return criterion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSESSMENT.CRITERION
     *
     * @param criterion the value for ASSESSMENT.CRITERION
     *
     * @mbggenerated
     */
    public void setCriterion(BigDecimal criterion) {
        this.criterion = criterion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSESSMENT.LAST_REWARD
     *
     * @return the value of ASSESSMENT.LAST_REWARD
     *
     * @mbggenerated
     */
    public BigDecimal getLastReward() {
        return lastReward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSESSMENT.LAST_REWARD
     *
     * @param lastReward the value for ASSESSMENT.LAST_REWARD
     *
     * @mbggenerated
     */
    public void setLastReward(BigDecimal lastReward) {
        this.lastReward = lastReward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSESSMENT.LAST_FORWARD_REWARD
     *
     * @return the value of ASSESSMENT.LAST_FORWARD_REWARD
     *
     * @mbggenerated
     */
    public BigDecimal getLastForwardReward() {
        return lastForwardReward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSESSMENT.LAST_FORWARD_REWARD
     *
     * @param lastForwardReward the value for ASSESSMENT.LAST_FORWARD_REWARD
     *
     * @mbggenerated
     */
    public void setLastForwardReward(BigDecimal lastForwardReward) {
        this.lastForwardReward = lastForwardReward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSESSMENT.LAST_SETTLEMENT
     *
     * @return the value of ASSESSMENT.LAST_SETTLEMENT
     *
     * @mbggenerated
     */
    public BigDecimal getLastSettlement() {
        return lastSettlement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSESSMENT.LAST_SETTLEMENT
     *
     * @param lastSettlement the value for ASSESSMENT.LAST_SETTLEMENT
     *
     * @mbggenerated
     */
    public void setLastSettlement(BigDecimal lastSettlement) {
        this.lastSettlement = lastSettlement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSESSMENT.FORWARD_REWARD
     *
     * @return the value of ASSESSMENT.FORWARD_REWARD
     *
     * @mbggenerated
     */
    public BigDecimal getForwardReward() {
        return forwardReward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSESSMENT.FORWARD_REWARD
     *
     * @param forwardReward the value for ASSESSMENT.FORWARD_REWARD
     *
     * @mbggenerated
     */
    public void setForwardReward(BigDecimal forwardReward) {
        this.forwardReward = forwardReward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSESSMENT.REWARD
     *
     * @return the value of ASSESSMENT.REWARD
     *
     * @mbggenerated
     */
    public BigDecimal getReward() {
        return reward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSESSMENT.REWARD
     *
     * @param reward the value for ASSESSMENT.REWARD
     *
     * @mbggenerated
     */
    public void setReward(BigDecimal reward) {
        this.reward = reward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSESSMENT.DOUBLE_REWARD
     *
     * @return the value of ASSESSMENT.DOUBLE_REWARD
     *
     * @mbggenerated
     */
    public BigDecimal getDoubleReward() {
        return doubleReward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSESSMENT.DOUBLE_REWARD
     *
     * @param doubleReward the value for ASSESSMENT.DOUBLE_REWARD
     *
     * @mbggenerated
     */
    public void setDoubleReward(BigDecimal doubleReward) {
        this.doubleReward = doubleReward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSESSMENT.STATE
     *
     * @return the value of ASSESSMENT.STATE
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSESSMENT.STATE
     *
     * @param state the value for ASSESSMENT.STATE
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSESSMENT.CREATE_DATE
     *
     * @return the value of ASSESSMENT.CREATE_DATE
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSESSMENT.CREATE_DATE
     *
     * @param createDate the value for ASSESSMENT.CREATE_DATE
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}