package com.telecomjs.beans;

import java.math.BigDecimal;
import java.util.Date;

public class AssessmentItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSESSMENT_ITEM.ITEM_ID
     *
     * @mbggenerated
     */
    private Integer itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSESSMENT_ITEM.ROLE_CODE
     *
     * @mbggenerated
     */
    private String roleCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSESSMENT_ITEM.ASSESSMENT_PERCENT
     *
     * @mbggenerated
     */
    private Short assessmentPercent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSESSMENT_ITEM.ITEM_NAME
     *
     * @mbggenerated
     */
    private String itemName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSESSMENT_ITEM.CRITERION_SCORE
     *
     * @mbggenerated
     */
    private BigDecimal criterionScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSESSMENT_ITEM.CRITERION_DETAIL
     *
     * @mbggenerated
     */
    private String criterionDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSESSMENT_ITEM.ITEM_CATEGORY_ID
     *
     * @mbggenerated
     */
    private Integer itemCategoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSESSMENT_ITEM.STATE
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSESSMENT_ITEM.STATE_DATE
     *
     * @mbggenerated
     */
    private Date stateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSESSMENT_ITEM.ITEM_ID
     *
     * @return the value of ASSESSMENT_ITEM.ITEM_ID
     *
     * @mbggenerated
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSESSMENT_ITEM.ITEM_ID
     *
     * @param itemId the value for ASSESSMENT_ITEM.ITEM_ID
     *
     * @mbggenerated
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSESSMENT_ITEM.ROLE_CODE
     *
     * @return the value of ASSESSMENT_ITEM.ROLE_CODE
     *
     * @mbggenerated
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSESSMENT_ITEM.ROLE_CODE
     *
     * @param roleCode the value for ASSESSMENT_ITEM.ROLE_CODE
     *
     * @mbggenerated
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode == null ? null : roleCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSESSMENT_ITEM.ASSESSMENT_PERCENT
     *
     * @return the value of ASSESSMENT_ITEM.ASSESSMENT_PERCENT
     *
     * @mbggenerated
     */
    public Short getAssessmentPercent() {
        return assessmentPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSESSMENT_ITEM.ASSESSMENT_PERCENT
     *
     * @param assessmentPercent the value for ASSESSMENT_ITEM.ASSESSMENT_PERCENT
     *
     * @mbggenerated
     */
    public void setAssessmentPercent(Short assessmentPercent) {
        this.assessmentPercent = assessmentPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSESSMENT_ITEM.ITEM_NAME
     *
     * @return the value of ASSESSMENT_ITEM.ITEM_NAME
     *
     * @mbggenerated
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSESSMENT_ITEM.ITEM_NAME
     *
     * @param itemName the value for ASSESSMENT_ITEM.ITEM_NAME
     *
     * @mbggenerated
     */
    public void setItemName(String itemName) {
        this.itemName = itemName == null ? null : itemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSESSMENT_ITEM.CRITERION_SCORE
     *
     * @return the value of ASSESSMENT_ITEM.CRITERION_SCORE
     *
     * @mbggenerated
     */
    public BigDecimal getCriterionScore() {
        return criterionScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSESSMENT_ITEM.CRITERION_SCORE
     *
     * @param criterionScore the value for ASSESSMENT_ITEM.CRITERION_SCORE
     *
     * @mbggenerated
     */
    public void setCriterionScore(BigDecimal criterionScore) {
        this.criterionScore = criterionScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSESSMENT_ITEM.CRITERION_DETAIL
     *
     * @return the value of ASSESSMENT_ITEM.CRITERION_DETAIL
     *
     * @mbggenerated
     */
    public String getCriterionDetail() {
        return criterionDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSESSMENT_ITEM.CRITERION_DETAIL
     *
     * @param criterionDetail the value for ASSESSMENT_ITEM.CRITERION_DETAIL
     *
     * @mbggenerated
     */
    public void setCriterionDetail(String criterionDetail) {
        this.criterionDetail = criterionDetail == null ? null : criterionDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSESSMENT_ITEM.ITEM_CATEGORY_ID
     *
     * @return the value of ASSESSMENT_ITEM.ITEM_CATEGORY_ID
     *
     * @mbggenerated
     */
    public Integer getItemCategoryId() {
        return itemCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSESSMENT_ITEM.ITEM_CATEGORY_ID
     *
     * @param itemCategoryId the value for ASSESSMENT_ITEM.ITEM_CATEGORY_ID
     *
     * @mbggenerated
     */
    public void setItemCategoryId(int itemCategoryId) {
        this.itemCategoryId = itemCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSESSMENT_ITEM.STATE
     *
     * @return the value of ASSESSMENT_ITEM.STATE
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSESSMENT_ITEM.STATE
     *
     * @param state the value for ASSESSMENT_ITEM.STATE
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSESSMENT_ITEM.STATE_DATE
     *
     * @return the value of ASSESSMENT_ITEM.STATE_DATE
     *
     * @mbggenerated
     */
    public Date getStateDate() {
        return stateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSESSMENT_ITEM.STATE_DATE
     *
     * @param stateDate the value for ASSESSMENT_ITEM.STATE_DATE
     *
     * @mbggenerated
     */
    public void setStateDate(Date stateDate) {
        this.stateDate = stateDate;
    }
}