package com.telecomjs.beans;

import java.math.BigDecimal;
import java.util.Date;

public class AssessmentEvent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSESSMENT_EVENT.EVENT_ID
     *
     * @mbggenerated
     */
    private Integer eventId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSESSMENT_EVENT.BILLING_CYCLE_ID
     *
     * @mbggenerated
     */
    private Integer billingCycleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSESSMENT_EVENT.FILE_NAME
     *
     * @mbggenerated
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSESSMENT_EVENT.STAFF_ID
     *
     * @mbggenerated
     */
    private Integer staffId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSESSMENT_EVENT.RECORD_ROW
     *
     * @mbggenerated
     */
    private Integer recordRow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSESSMENT_EVENT.AMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSESSMENT_EVENT.STATE_DATE
     *
     * @mbggenerated
     */
    private Date stateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSESSMENT_EVENT.CREATE_DATE
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSESSMENT_EVENT.STATE
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSESSMENT_EVENT.EVENT_ID
     *
     * @return the value of ASSESSMENT_EVENT.EVENT_ID
     *
     * @mbggenerated
     */
    public Integer getEventId() {
        return eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSESSMENT_EVENT.EVENT_ID
     *
     * @param eventId the value for ASSESSMENT_EVENT.EVENT_ID
     *
     * @mbggenerated
     */
    public void setEventId(Integer eventId) {
        this.eventId = eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSESSMENT_EVENT.BILLING_CYCLE_ID
     *
     * @return the value of ASSESSMENT_EVENT.BILLING_CYCLE_ID
     *
     * @mbggenerated
     */
    public Integer getBillingCycleId() {
        return billingCycleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSESSMENT_EVENT.BILLING_CYCLE_ID
     *
     * @param billingCycleId the value for ASSESSMENT_EVENT.BILLING_CYCLE_ID
     *
     * @mbggenerated
     */
    public void setBillingCycleId(Integer billingCycleId) {
        this.billingCycleId = billingCycleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSESSMENT_EVENT.FILE_NAME
     *
     * @return the value of ASSESSMENT_EVENT.FILE_NAME
     *
     * @mbggenerated
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSESSMENT_EVENT.FILE_NAME
     *
     * @param fileName the value for ASSESSMENT_EVENT.FILE_NAME
     *
     * @mbggenerated
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSESSMENT_EVENT.STAFF_ID
     *
     * @return the value of ASSESSMENT_EVENT.STAFF_ID
     *
     * @mbggenerated
     */
    public Integer getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSESSMENT_EVENT.STAFF_ID
     *
     * @param staffId the value for ASSESSMENT_EVENT.STAFF_ID
     *
     * @mbggenerated
     */
    public void setStaffId(Integer staffId) {
        this.staffId = staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSESSMENT_EVENT.RECORD_ROW
     *
     * @return the value of ASSESSMENT_EVENT.RECORD_ROW
     *
     * @mbggenerated
     */
    public Integer getRecordRow() {
        return recordRow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSESSMENT_EVENT.RECORD_ROW
     *
     * @param recordRow the value for ASSESSMENT_EVENT.RECORD_ROW
     *
     * @mbggenerated
     */
    public void setRecordRow(Integer recordRow) {
        this.recordRow = recordRow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSESSMENT_EVENT.AMOUNT
     *
     * @return the value of ASSESSMENT_EVENT.AMOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSESSMENT_EVENT.AMOUNT
     *
     * @param amount the value for ASSESSMENT_EVENT.AMOUNT
     *
     * @mbggenerated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSESSMENT_EVENT.STATE_DATE
     *
     * @return the value of ASSESSMENT_EVENT.STATE_DATE
     *
     * @mbggenerated
     */
    public Date getStateDate() {
        return stateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSESSMENT_EVENT.STATE_DATE
     *
     * @param stateDate the value for ASSESSMENT_EVENT.STATE_DATE
     *
     * @mbggenerated
     */
    public void setStateDate(Date stateDate) {
        this.stateDate = stateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSESSMENT_EVENT.CREATE_DATE
     *
     * @return the value of ASSESSMENT_EVENT.CREATE_DATE
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSESSMENT_EVENT.CREATE_DATE
     *
     * @param createDate the value for ASSESSMENT_EVENT.CREATE_DATE
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSESSMENT_EVENT.STATE
     *
     * @return the value of ASSESSMENT_EVENT.STATE
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSESSMENT_EVENT.STATE
     *
     * @param state the value for ASSESSMENT_EVENT.STATE
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }
}