package com.telecomjs.beans;

import java.util.Date;

public class AssessmentSignature {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSESSMENT_SIGNATURE.SIGNATURE_ID
     *
     * @mbggenerated
     */
    private Integer signatureId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSESSMENT_SIGNATURE.ASSESSMENT_ID
     *
     * @mbggenerated
     */
    private Integer assessmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSESSMENT_SIGNATURE.FILENAME
     *
     * @mbggenerated
     */
    private String filename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSESSMENT_SIGNATURE.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSESSMENT_SIGNATURE.STATE
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSESSMENT_SIGNATURE.STATE_DATE
     *
     * @mbggenerated
     */
    private Date stateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSESSMENT_SIGNATURE.PIC
     *
     * @mbggenerated
     */
    private byte[] pic;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSESSMENT_SIGNATURE.SIGNATURE_ID
     *
     * @return the value of ASSESSMENT_SIGNATURE.SIGNATURE_ID
     *
     * @mbggenerated
     */
    public Integer getSignatureId() {
        return signatureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSESSMENT_SIGNATURE.SIGNATURE_ID
     *
     * @param signatureId the value for ASSESSMENT_SIGNATURE.SIGNATURE_ID
     *
     * @mbggenerated
     */
    public void setSignatureId(Integer signatureId) {
        this.signatureId = signatureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSESSMENT_SIGNATURE.ASSESSMENT_ID
     *
     * @return the value of ASSESSMENT_SIGNATURE.ASSESSMENT_ID
     *
     * @mbggenerated
     */
    public Integer getAssessmentId() {
        return assessmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSESSMENT_SIGNATURE.ASSESSMENT_ID
     *
     * @param assessmentId the value for ASSESSMENT_SIGNATURE.ASSESSMENT_ID
     *
     * @mbggenerated
     */
    public void setAssessmentId(Integer assessmentId) {
        this.assessmentId = assessmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSESSMENT_SIGNATURE.FILENAME
     *
     * @return the value of ASSESSMENT_SIGNATURE.FILENAME
     *
     * @mbggenerated
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSESSMENT_SIGNATURE.FILENAME
     *
     * @param filename the value for ASSESSMENT_SIGNATURE.FILENAME
     *
     * @mbggenerated
     */
    public void setFilename(String filename) {
        this.filename = filename == null ? null : filename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSESSMENT_SIGNATURE.REMARK
     *
     * @return the value of ASSESSMENT_SIGNATURE.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSESSMENT_SIGNATURE.REMARK
     *
     * @param remark the value for ASSESSMENT_SIGNATURE.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSESSMENT_SIGNATURE.STATE
     *
     * @return the value of ASSESSMENT_SIGNATURE.STATE
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSESSMENT_SIGNATURE.STATE
     *
     * @param state the value for ASSESSMENT_SIGNATURE.STATE
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSESSMENT_SIGNATURE.STATE_DATE
     *
     * @return the value of ASSESSMENT_SIGNATURE.STATE_DATE
     *
     * @mbggenerated
     */
    public Date getStateDate() {
        return stateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSESSMENT_SIGNATURE.STATE_DATE
     *
     * @param stateDate the value for ASSESSMENT_SIGNATURE.STATE_DATE
     *
     * @mbggenerated
     */
    public void setStateDate(Date stateDate) {
        this.stateDate = stateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSESSMENT_SIGNATURE.PIC
     *
     * @return the value of ASSESSMENT_SIGNATURE.PIC
     *
     * @mbggenerated
     */
    public byte[] getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSESSMENT_SIGNATURE.PIC
     *
     * @param pic the value for ASSESSMENT_SIGNATURE.PIC
     *
     * @mbggenerated
     */
    public void setPic(byte[] pic) {
        this.pic = pic;
    }
}