package com.telecomjs.beans;

import java.math.BigDecimal;
import java.util.Date;

public class AssessmentSubscriber {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSESSMENT_SUBSCRIBER.SUBSCRIBER_ID
     *
     * @mbggenerated
     */
    private Integer subscriberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSESSMENT_SUBSCRIBER.ASSESSMENT_EVENT_ID
     *
     * @mbggenerated
     */
    private Integer assessmentEventId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSESSMENT_SUBSCRIBER.ASSESSMENT_ID
     *
     * @mbggenerated
     */
    private Integer assessmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSESSMENT_SUBSCRIBER.ZONE_ID
     *
     * @mbggenerated
     */
    private Long zoneId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSESSMENT_SUBSCRIBER.AMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSESSMENT_SUBSCRIBER.TO_STAFF_ID
     *
     * @mbggenerated
     */
    private Integer toStaffId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSESSMENT_SUBSCRIBER.STATE_DATE
     *
     * @mbggenerated
     */
    private Date stateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSESSMENT_SUBSCRIBER.STATE
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSESSMENT_SUBSCRIBER.SUBSCRIBER_ID
     *
     * @return the value of ASSESSMENT_SUBSCRIBER.SUBSCRIBER_ID
     *
     * @mbggenerated
     */
    public Integer getSubscriberId() {
        return subscriberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSESSMENT_SUBSCRIBER.SUBSCRIBER_ID
     *
     * @param subscriberId the value for ASSESSMENT_SUBSCRIBER.SUBSCRIBER_ID
     *
     * @mbggenerated
     */
    public void setSubscriberId(Integer subscriberId) {
        this.subscriberId = subscriberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSESSMENT_SUBSCRIBER.ASSESSMENT_EVENT_ID
     *
     * @return the value of ASSESSMENT_SUBSCRIBER.ASSESSMENT_EVENT_ID
     *
     * @mbggenerated
     */
    public Integer getAssessmentEventId() {
        return assessmentEventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSESSMENT_SUBSCRIBER.ASSESSMENT_EVENT_ID
     *
     * @param assessmentEventId the value for ASSESSMENT_SUBSCRIBER.ASSESSMENT_EVENT_ID
     *
     * @mbggenerated
     */
    public void setAssessmentEventId(Integer assessmentEventId) {
        this.assessmentEventId = assessmentEventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSESSMENT_SUBSCRIBER.ASSESSMENT_ID
     *
     * @return the value of ASSESSMENT_SUBSCRIBER.ASSESSMENT_ID
     *
     * @mbggenerated
     */
    public Integer getAssessmentId() {
        return assessmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSESSMENT_SUBSCRIBER.ASSESSMENT_ID
     *
     * @param assessmentId the value for ASSESSMENT_SUBSCRIBER.ASSESSMENT_ID
     *
     * @mbggenerated
     */
    public void setAssessmentId(Integer assessmentId) {
        this.assessmentId = assessmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSESSMENT_SUBSCRIBER.ZONE_ID
     *
     * @return the value of ASSESSMENT_SUBSCRIBER.ZONE_ID
     *
     * @mbggenerated
     */
    public Long getZoneId() {
        return zoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSESSMENT_SUBSCRIBER.ZONE_ID
     *
     * @param zoneId the value for ASSESSMENT_SUBSCRIBER.ZONE_ID
     *
     * @mbggenerated
     */
    public void setZoneId(Long zoneId) {
        this.zoneId = zoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSESSMENT_SUBSCRIBER.AMOUNT
     *
     * @return the value of ASSESSMENT_SUBSCRIBER.AMOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSESSMENT_SUBSCRIBER.AMOUNT
     *
     * @param amount the value for ASSESSMENT_SUBSCRIBER.AMOUNT
     *
     * @mbggenerated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSESSMENT_SUBSCRIBER.TO_STAFF_ID
     *
     * @return the value of ASSESSMENT_SUBSCRIBER.TO_STAFF_ID
     *
     * @mbggenerated
     */
    public Integer getToStaffId() {
        return toStaffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSESSMENT_SUBSCRIBER.TO_STAFF_ID
     *
     * @param toStaffId the value for ASSESSMENT_SUBSCRIBER.TO_STAFF_ID
     *
     * @mbggenerated
     */
    public void setToStaffId(Integer toStaffId) {
        this.toStaffId = toStaffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSESSMENT_SUBSCRIBER.STATE_DATE
     *
     * @return the value of ASSESSMENT_SUBSCRIBER.STATE_DATE
     *
     * @mbggenerated
     */
    public Date getStateDate() {
        return stateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSESSMENT_SUBSCRIBER.STATE_DATE
     *
     * @param stateDate the value for ASSESSMENT_SUBSCRIBER.STATE_DATE
     *
     * @mbggenerated
     */
    public void setStateDate(Date stateDate) {
        this.stateDate = stateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSESSMENT_SUBSCRIBER.STATE
     *
     * @return the value of ASSESSMENT_SUBSCRIBER.STATE
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSESSMENT_SUBSCRIBER.STATE
     *
     * @param state the value for ASSESSMENT_SUBSCRIBER.STATE
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }
}