package com.telecomjs.beans;

import java.util.Date;

public class AssessmentLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSESSMENT_LOG.LOG_ID
     *
     * @mbggenerated
     */
    private Integer logId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSESSMENT_LOG.ASSESSMENT_ID
     *
     * @mbggenerated
     */
    private Integer assessmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSESSMENT_LOG.OPERATION
     *
     * @mbggenerated
     */
    private String operation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSESSMENT_LOG.CSS_STAFF_ID
     *
     * @mbggenerated
     */
    private Long cssStaffId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSESSMENT_LOG.STAFF_NAME
     *
     * @mbggenerated
     */
    private String staffName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSESSMENT_LOG.PRE_STATE
     *
     * @mbggenerated
     */
    private String preState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSESSMENT_LOG.NEXT_STATE
     *
     * @mbggenerated
     */
    private String nextState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSESSMENT_LOG.STATE_DATE
     *
     * @mbggenerated
     */
    private Date stateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSESSMENT_LOG.LOG_ID
     *
     * @return the value of ASSESSMENT_LOG.LOG_ID
     *
     * @mbggenerated
     */
    public Integer getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSESSMENT_LOG.LOG_ID
     *
     * @param logId the value for ASSESSMENT_LOG.LOG_ID
     *
     * @mbggenerated
     */
    public void setLogId(Integer logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSESSMENT_LOG.ASSESSMENT_ID
     *
     * @return the value of ASSESSMENT_LOG.ASSESSMENT_ID
     *
     * @mbggenerated
     */
    public Integer getAssessmentId() {
        return assessmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSESSMENT_LOG.ASSESSMENT_ID
     *
     * @param assessmentId the value for ASSESSMENT_LOG.ASSESSMENT_ID
     *
     * @mbggenerated
     */
    public void setAssessmentId(Integer assessmentId) {
        this.assessmentId = assessmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSESSMENT_LOG.OPERATION
     *
     * @return the value of ASSESSMENT_LOG.OPERATION
     *
     * @mbggenerated
     */
    public String getOperation() {
        return operation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSESSMENT_LOG.OPERATION
     *
     * @param operation the value for ASSESSMENT_LOG.OPERATION
     *
     * @mbggenerated
     */
    public void setOperation(String operation) {
        this.operation = operation == null ? null : operation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSESSMENT_LOG.CSS_STAFF_ID
     *
     * @return the value of ASSESSMENT_LOG.CSS_STAFF_ID
     *
     * @mbggenerated
     */
    public Long getCssStaffId() {
        return cssStaffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSESSMENT_LOG.CSS_STAFF_ID
     *
     * @param cssStaffId the value for ASSESSMENT_LOG.CSS_STAFF_ID
     *
     * @mbggenerated
     */
    public void setCssStaffId(Long cssStaffId) {
        this.cssStaffId = cssStaffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSESSMENT_LOG.STAFF_NAME
     *
     * @return the value of ASSESSMENT_LOG.STAFF_NAME
     *
     * @mbggenerated
     */
    public String getStaffName() {
        return staffName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSESSMENT_LOG.STAFF_NAME
     *
     * @param staffName the value for ASSESSMENT_LOG.STAFF_NAME
     *
     * @mbggenerated
     */
    public void setStaffName(String staffName) {
        this.staffName = staffName == null ? null : staffName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSESSMENT_LOG.PRE_STATE
     *
     * @return the value of ASSESSMENT_LOG.PRE_STATE
     *
     * @mbggenerated
     */
    public String getPreState() {
        return preState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSESSMENT_LOG.PRE_STATE
     *
     * @param preState the value for ASSESSMENT_LOG.PRE_STATE
     *
     * @mbggenerated
     */
    public void setPreState(String preState) {
        this.preState = preState == null ? null : preState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSESSMENT_LOG.NEXT_STATE
     *
     * @return the value of ASSESSMENT_LOG.NEXT_STATE
     *
     * @mbggenerated
     */
    public String getNextState() {
        return nextState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSESSMENT_LOG.NEXT_STATE
     *
     * @param nextState the value for ASSESSMENT_LOG.NEXT_STATE
     *
     * @mbggenerated
     */
    public void setNextState(String nextState) {
        this.nextState = nextState == null ? null : nextState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSESSMENT_LOG.STATE_DATE
     *
     * @return the value of ASSESSMENT_LOG.STATE_DATE
     *
     * @mbggenerated
     */
    public Date getStateDate() {
        return stateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSESSMENT_LOG.STATE_DATE
     *
     * @param stateDate the value for ASSESSMENT_LOG.STATE_DATE
     *
     * @mbggenerated
     */
    public void setStateDate(Date stateDate) {
        this.stateDate = stateDate;
    }
}