package com.telecomjs.beans;

public class BillingCycle {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILLING_CYCLE.BILLING_CYCLE_ID
     *
     * @mbggenerated
     */
    private Integer billingCycleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILLING_CYCLE.STATE
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILLING_CYCLE.BILLING_CYCLE_ID
     *
     * @return the value of BILLING_CYCLE.BILLING_CYCLE_ID
     *
     * @mbggenerated
     */
    public Integer getBillingCycleId() {
        return billingCycleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILLING_CYCLE.BILLING_CYCLE_ID
     *
     * @param billingCycleId the value for BILLING_CYCLE.BILLING_CYCLE_ID
     *
     * @mbggenerated
     */
    public void setBillingCycleId(Integer billingCycleId) {
        this.billingCycleId = billingCycleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILLING_CYCLE.STATE
     *
     * @return the value of BILLING_CYCLE.STATE
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILLING_CYCLE.STATE
     *
     * @param state the value for BILLING_CYCLE.STATE
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }
}