package com.telecomjs.beans;

public class ItemCategory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ITEM_CATEGORY.CATEGORY_ID
     *
     * @mbggenerated
     */
    private Integer categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ITEM_CATEGORY.ROLE_CODE
     *
     * @mbggenerated
     */
    private String roleCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ITEM_CATEGORY.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ITEM_CATEGORY.CATEGORY_ID
     *
     * @return the value of ITEM_CATEGORY.CATEGORY_ID
     *
     * @mbggenerated
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ITEM_CATEGORY.CATEGORY_ID
     *
     * @param categoryId the value for ITEM_CATEGORY.CATEGORY_ID
     *
     * @mbggenerated
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ITEM_CATEGORY.ROLE_CODE
     *
     * @return the value of ITEM_CATEGORY.ROLE_CODE
     *
     * @mbggenerated
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ITEM_CATEGORY.ROLE_CODE
     *
     * @param roleCode the value for ITEM_CATEGORY.ROLE_CODE
     *
     * @mbggenerated
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode == null ? null : roleCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ITEM_CATEGORY.NAME
     *
     * @return the value of ITEM_CATEGORY.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ITEM_CATEGORY.NAME
     *
     * @param name the value for ITEM_CATEGORY.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}