package com.telecomjs.beans;

import java.util.Date;

public class Staff {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF.STAFF_ID
     *
     * @mbggenerated
     */
    private Integer staffId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF.MOBILE
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF.IDENTIFIEDCODE
     *
     * @mbggenerated
     */
    private String identifiedcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF.CSS_STAFF_NUMBER
     *
     * @mbggenerated
     */
    private String cssStaffNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF.BSS_STAFF_NUMBER
     *
     * @mbggenerated
     */
    private String bssStaffNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF.PASSWORD
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF.ROLE_ID
     *
     * @mbggenerated
     */
    private Short roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF.STATE
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF.CREATE_DATE
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF.STATE_DATE
     *
     * @mbggenerated
     */
    private Date stateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF.STAFF_ID
     *
     * @return the value of STAFF.STAFF_ID
     *
     * @mbggenerated
     */
    public Integer getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF.STAFF_ID
     *
     * @param staffId the value for STAFF.STAFF_ID
     *
     * @mbggenerated
     */
    public void setStaffId(Integer staffId) {
        this.staffId = staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF.NAME
     *
     * @return the value of STAFF.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF.NAME
     *
     * @param name the value for STAFF.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF.MOBILE
     *
     * @return the value of STAFF.MOBILE
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF.MOBILE
     *
     * @param mobile the value for STAFF.MOBILE
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF.IDENTIFIEDCODE
     *
     * @return the value of STAFF.IDENTIFIEDCODE
     *
     * @mbggenerated
     */
    public String getIdentifiedcode() {
        return identifiedcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF.IDENTIFIEDCODE
     *
     * @param identifiedcode the value for STAFF.IDENTIFIEDCODE
     *
     * @mbggenerated
     */
    public void setIdentifiedcode(String identifiedcode) {
        this.identifiedcode = identifiedcode == null ? null : identifiedcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF.CSS_STAFF_NUMBER
     *
     * @return the value of STAFF.CSS_STAFF_NUMBER
     *
     * @mbggenerated
     */
    public String getCssStaffNumber() {
        return cssStaffNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF.CSS_STAFF_NUMBER
     *
     * @param cssStaffNumber the value for STAFF.CSS_STAFF_NUMBER
     *
     * @mbggenerated
     */
    public void setCssStaffNumber(String cssStaffNumber) {
        this.cssStaffNumber = cssStaffNumber == null ? null : cssStaffNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF.BSS_STAFF_NUMBER
     *
     * @return the value of STAFF.BSS_STAFF_NUMBER
     *
     * @mbggenerated
     */
    public String getBssStaffNumber() {
        return bssStaffNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF.BSS_STAFF_NUMBER
     *
     * @param bssStaffNumber the value for STAFF.BSS_STAFF_NUMBER
     *
     * @mbggenerated
     */
    public void setBssStaffNumber(String bssStaffNumber) {
        this.bssStaffNumber = bssStaffNumber == null ? null : bssStaffNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF.PASSWORD
     *
     * @return the value of STAFF.PASSWORD
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF.PASSWORD
     *
     * @param password the value for STAFF.PASSWORD
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF.ROLE_ID
     *
     * @return the value of STAFF.ROLE_ID
     *
     * @mbggenerated
     */
    public Short getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF.ROLE_ID
     *
     * @param roleId the value for STAFF.ROLE_ID
     *
     * @mbggenerated
     */
    public void setRoleId(Short roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF.STATE
     *
     * @return the value of STAFF.STATE
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF.STATE
     *
     * @param state the value for STAFF.STATE
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF.CREATE_DATE
     *
     * @return the value of STAFF.CREATE_DATE
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF.CREATE_DATE
     *
     * @param createDate the value for STAFF.CREATE_DATE
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF.STATE_DATE
     *
     * @return the value of STAFF.STATE_DATE
     *
     * @mbggenerated
     */
    public Date getStateDate() {
        return stateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF.STATE_DATE
     *
     * @param stateDate the value for STAFF.STATE_DATE
     *
     * @mbggenerated
     */
    public void setStateDate(Date stateDate) {
        this.stateDate = stateDate;
    }
}