package com.telecomjs.beans;

import java.math.BigDecimal;
import java.util.Date;

public class StaffAssessment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_ASSESSMENT.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_ASSESSMENT.ASSESSMENT_ID
     *
     * @mbggenerated
     */
    private Integer assessmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_ASSESSMENT.BILLING_CYCLE
     *
     * @mbggenerated
     */
    private Integer billingCycle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_ASSESSMENT.CSS_STAFF_ID
     *
     * @mbggenerated
     */
    private Long cssStaffId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_ASSESSMENT.ASSESSMENT_AMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal assessmentAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_ASSESSMENT.PERSONAL_AMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal personalAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_ASSESSMENT.ROLE_NAME
     *
     * @mbggenerated
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_ASSESSMENT.STATE
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_ASSESSMENT.STATE_DATE
     *
     * @mbggenerated
     */
    private Date stateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_ASSESSMENT.STAFF_NAME
     *
     * @mbggenerated
     */
    private String staffName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_ASSESSMENT.ID
     *
     * @return the value of STAFF_ASSESSMENT.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_ASSESSMENT.ID
     *
     * @param id the value for STAFF_ASSESSMENT.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_ASSESSMENT.ASSESSMENT_ID
     *
     * @return the value of STAFF_ASSESSMENT.ASSESSMENT_ID
     *
     * @mbggenerated
     */
    public Integer getAssessmentId() {
        return assessmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_ASSESSMENT.ASSESSMENT_ID
     *
     * @param assessmentId the value for STAFF_ASSESSMENT.ASSESSMENT_ID
     *
     * @mbggenerated
     */
    public void setAssessmentId(Integer assessmentId) {
        this.assessmentId = assessmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_ASSESSMENT.BILLING_CYCLE
     *
     * @return the value of STAFF_ASSESSMENT.BILLING_CYCLE
     *
     * @mbggenerated
     */
    public Integer getBillingCycle() {
        return billingCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_ASSESSMENT.BILLING_CYCLE
     *
     * @param billingCycle the value for STAFF_ASSESSMENT.BILLING_CYCLE
     *
     * @mbggenerated
     */
    public void setBillingCycle(Integer billingCycle) {
        this.billingCycle = billingCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_ASSESSMENT.CSS_STAFF_ID
     *
     * @return the value of STAFF_ASSESSMENT.CSS_STAFF_ID
     *
     * @mbggenerated
     */
    public Long getCssStaffId() {
        return cssStaffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_ASSESSMENT.CSS_STAFF_ID
     *
     * @param cssStaffId the value for STAFF_ASSESSMENT.CSS_STAFF_ID
     *
     * @mbggenerated
     */
    public void setCssStaffId(Long cssStaffId) {
        this.cssStaffId = cssStaffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_ASSESSMENT.ASSESSMENT_AMOUNT
     *
     * @return the value of STAFF_ASSESSMENT.ASSESSMENT_AMOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getAssessmentAmount() {
        return assessmentAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_ASSESSMENT.ASSESSMENT_AMOUNT
     *
     * @param assessmentAmount the value for STAFF_ASSESSMENT.ASSESSMENT_AMOUNT
     *
     * @mbggenerated
     */
    public void setAssessmentAmount(BigDecimal assessmentAmount) {
        this.assessmentAmount = assessmentAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_ASSESSMENT.PERSONAL_AMOUNT
     *
     * @return the value of STAFF_ASSESSMENT.PERSONAL_AMOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getPersonalAmount() {
        return personalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_ASSESSMENT.PERSONAL_AMOUNT
     *
     * @param personalAmount the value for STAFF_ASSESSMENT.PERSONAL_AMOUNT
     *
     * @mbggenerated
     */
    public void setPersonalAmount(BigDecimal personalAmount) {
        this.personalAmount = personalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_ASSESSMENT.ROLE_NAME
     *
     * @return the value of STAFF_ASSESSMENT.ROLE_NAME
     *
     * @mbggenerated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_ASSESSMENT.ROLE_NAME
     *
     * @param roleName the value for STAFF_ASSESSMENT.ROLE_NAME
     *
     * @mbggenerated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_ASSESSMENT.STATE
     *
     * @return the value of STAFF_ASSESSMENT.STATE
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_ASSESSMENT.STATE
     *
     * @param state the value for STAFF_ASSESSMENT.STATE
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_ASSESSMENT.STATE_DATE
     *
     * @return the value of STAFF_ASSESSMENT.STATE_DATE
     *
     * @mbggenerated
     */
    public Date getStateDate() {
        return stateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_ASSESSMENT.STATE_DATE
     *
     * @param stateDate the value for STAFF_ASSESSMENT.STATE_DATE
     *
     * @mbggenerated
     */
    public void setStateDate(Date stateDate) {
        this.stateDate = stateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_ASSESSMENT.STAFF_NAME
     *
     * @return the value of STAFF_ASSESSMENT.STAFF_NAME
     *
     * @mbggenerated
     */
    public String getStaffName() {
        return staffName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_ASSESSMENT.STAFF_NAME
     *
     * @param staffName the value for STAFF_ASSESSMENT.STAFF_NAME
     *
     * @mbggenerated
     */
    public void setStaffName(String staffName) {
        this.staffName = staffName == null ? null : staffName.trim();
    }
}