package com.telecomjs.beans;

import java.util.Date;

public class StaffAssessmentLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_ASSESSMENT_LOG.LOG_ID
     *
     * @mbggenerated
     */
    private Integer logId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_ASSESSMENT_LOG.STAFF_ASSESSMENT_ID
     *
     * @mbggenerated
     */
    private Integer staffAssessmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_ASSESSMENT_LOG.OPERATION_CODE
     *
     * @mbggenerated
     */
    private String operationCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_ASSESSMENT_LOG.STAFF_ID
     *
     * @mbggenerated
     */
    private Integer staffId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_ASSESSMENT_LOG.STATE_DATE
     *
     * @mbggenerated
     */
    private Date stateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_ASSESSMENT_LOG.LOG_ID
     *
     * @return the value of STAFF_ASSESSMENT_LOG.LOG_ID
     *
     * @mbggenerated
     */
    public Integer getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_ASSESSMENT_LOG.LOG_ID
     *
     * @param logId the value for STAFF_ASSESSMENT_LOG.LOG_ID
     *
     * @mbggenerated
     */
    public void setLogId(Integer logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_ASSESSMENT_LOG.STAFF_ASSESSMENT_ID
     *
     * @return the value of STAFF_ASSESSMENT_LOG.STAFF_ASSESSMENT_ID
     *
     * @mbggenerated
     */
    public Integer getStaffAssessmentId() {
        return staffAssessmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_ASSESSMENT_LOG.STAFF_ASSESSMENT_ID
     *
     * @param staffAssessmentId the value for STAFF_ASSESSMENT_LOG.STAFF_ASSESSMENT_ID
     *
     * @mbggenerated
     */
    public void setStaffAssessmentId(Integer staffAssessmentId) {
        this.staffAssessmentId = staffAssessmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_ASSESSMENT_LOG.OPERATION_CODE
     *
     * @return the value of STAFF_ASSESSMENT_LOG.OPERATION_CODE
     *
     * @mbggenerated
     */
    public String getOperationCode() {
        return operationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_ASSESSMENT_LOG.OPERATION_CODE
     *
     * @param operationCode the value for STAFF_ASSESSMENT_LOG.OPERATION_CODE
     *
     * @mbggenerated
     */
    public void setOperationCode(String operationCode) {
        this.operationCode = operationCode == null ? null : operationCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_ASSESSMENT_LOG.STAFF_ID
     *
     * @return the value of STAFF_ASSESSMENT_LOG.STAFF_ID
     *
     * @mbggenerated
     */
    public Integer getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_ASSESSMENT_LOG.STAFF_ID
     *
     * @param staffId the value for STAFF_ASSESSMENT_LOG.STAFF_ID
     *
     * @mbggenerated
     */
    public void setStaffId(Integer staffId) {
        this.staffId = staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_ASSESSMENT_LOG.STATE_DATE
     *
     * @return the value of STAFF_ASSESSMENT_LOG.STATE_DATE
     *
     * @mbggenerated
     */
    public Date getStateDate() {
        return stateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_ASSESSMENT_LOG.STATE_DATE
     *
     * @param stateDate the value for STAFF_ASSESSMENT_LOG.STATE_DATE
     *
     * @mbggenerated
     */
    public void setStateDate(Date stateDate) {
        this.stateDate = stateDate;
    }
}