package com.telecomjs.beans;

import java.math.BigDecimal;
import java.util.Date;

public class ZoneMarkAssessment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZONE_MARK_ASSESSMENT.MARK_ID
     *
     * @mbggenerated
     */
    private Long markId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZONE_MARK_ASSESSMENT.ZONE_ID
     *
     * @mbggenerated
     */
    private Long zoneId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZONE_MARK_ASSESSMENT.CHANNEL_TYPE
     *
     * @mbggenerated
     */
    private String channelType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZONE_MARK_ASSESSMENT.DELEGATE_TYPE
     *
     * @mbggenerated
     */
    private String delegateType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZONE_MARK_ASSESSMENT.ASSESSMENT_ID
     *
     * @mbggenerated
     */
    private Integer assessmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZONE_MARK_ASSESSMENT.BILLING_CYCLE
     *
     * @mbggenerated
     */
    private Long billingCycle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZONE_MARK_ASSESSMENT.SCORE
     *
     * @mbggenerated
     */
    private BigDecimal score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZONE_MARK_ASSESSMENT.CRITERION
     *
     * @mbggenerated
     */
    private BigDecimal criterion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZONE_MARK_ASSESSMENT.REWARD
     *
     * @mbggenerated
     */
    private BigDecimal reward;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZONE_MARK_ASSESSMENT.DOUBLE_REWARD
     *
     * @mbggenerated
     */
    private BigDecimal doubleReward;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZONE_MARK_ASSESSMENT.STATE_DATE
     *
     * @mbggenerated
     */
    private Date stateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZONE_MARK_ASSESSMENT.MARK_ID
     *
     * @return the value of ZONE_MARK_ASSESSMENT.MARK_ID
     *
     * @mbggenerated
     */
    public Long getMarkId() {
        return markId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZONE_MARK_ASSESSMENT.MARK_ID
     *
     * @param markId the value for ZONE_MARK_ASSESSMENT.MARK_ID
     *
     * @mbggenerated
     */
    public void setMarkId(Long markId) {
        this.markId = markId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZONE_MARK_ASSESSMENT.ZONE_ID
     *
     * @return the value of ZONE_MARK_ASSESSMENT.ZONE_ID
     *
     * @mbggenerated
     */
    public Long getZoneId() {
        return zoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZONE_MARK_ASSESSMENT.ZONE_ID
     *
     * @param zoneId the value for ZONE_MARK_ASSESSMENT.ZONE_ID
     *
     * @mbggenerated
     */
    public void setZoneId(Long zoneId) {
        this.zoneId = zoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZONE_MARK_ASSESSMENT.CHANNEL_TYPE
     *
     * @return the value of ZONE_MARK_ASSESSMENT.CHANNEL_TYPE
     *
     * @mbggenerated
     */
    public String getChannelType() {
        return channelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZONE_MARK_ASSESSMENT.CHANNEL_TYPE
     *
     * @param channelType the value for ZONE_MARK_ASSESSMENT.CHANNEL_TYPE
     *
     * @mbggenerated
     */
    public void setChannelType(String channelType) {
        this.channelType = channelType == null ? null : channelType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZONE_MARK_ASSESSMENT.DELEGATE_TYPE
     *
     * @return the value of ZONE_MARK_ASSESSMENT.DELEGATE_TYPE
     *
     * @mbggenerated
     */
    public String getDelegateType() {
        return delegateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZONE_MARK_ASSESSMENT.DELEGATE_TYPE
     *
     * @param delegateType the value for ZONE_MARK_ASSESSMENT.DELEGATE_TYPE
     *
     * @mbggenerated
     */
    public void setDelegateType(String delegateType) {
        this.delegateType = delegateType == null ? null : delegateType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZONE_MARK_ASSESSMENT.ASSESSMENT_ID
     *
     * @return the value of ZONE_MARK_ASSESSMENT.ASSESSMENT_ID
     *
     * @mbggenerated
     */
    public Integer getAssessmentId() {
        return assessmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZONE_MARK_ASSESSMENT.ASSESSMENT_ID
     *
     * @param assessmentId the value for ZONE_MARK_ASSESSMENT.ASSESSMENT_ID
     *
     * @mbggenerated
     */
    public void setAssessmentId(Integer assessmentId) {
        this.assessmentId = assessmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZONE_MARK_ASSESSMENT.BILLING_CYCLE
     *
     * @return the value of ZONE_MARK_ASSESSMENT.BILLING_CYCLE
     *
     * @mbggenerated
     */
    public Long getBillingCycle() {
        return billingCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZONE_MARK_ASSESSMENT.BILLING_CYCLE
     *
     * @param billingCycle the value for ZONE_MARK_ASSESSMENT.BILLING_CYCLE
     *
     * @mbggenerated
     */
    public void setBillingCycle(Long billingCycle) {
        this.billingCycle = billingCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZONE_MARK_ASSESSMENT.SCORE
     *
     * @return the value of ZONE_MARK_ASSESSMENT.SCORE
     *
     * @mbggenerated
     */
    public BigDecimal getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZONE_MARK_ASSESSMENT.SCORE
     *
     * @param score the value for ZONE_MARK_ASSESSMENT.SCORE
     *
     * @mbggenerated
     */
    public void setScore(BigDecimal score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZONE_MARK_ASSESSMENT.CRITERION
     *
     * @return the value of ZONE_MARK_ASSESSMENT.CRITERION
     *
     * @mbggenerated
     */
    public BigDecimal getCriterion() {
        return criterion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZONE_MARK_ASSESSMENT.CRITERION
     *
     * @param criterion the value for ZONE_MARK_ASSESSMENT.CRITERION
     *
     * @mbggenerated
     */
    public void setCriterion(BigDecimal criterion) {
        this.criterion = criterion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZONE_MARK_ASSESSMENT.REWARD
     *
     * @return the value of ZONE_MARK_ASSESSMENT.REWARD
     *
     * @mbggenerated
     */
    public BigDecimal getReward() {
        return reward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZONE_MARK_ASSESSMENT.REWARD
     *
     * @param reward the value for ZONE_MARK_ASSESSMENT.REWARD
     *
     * @mbggenerated
     */
    public void setReward(BigDecimal reward) {
        this.reward = reward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZONE_MARK_ASSESSMENT.DOUBLE_REWARD
     *
     * @return the value of ZONE_MARK_ASSESSMENT.DOUBLE_REWARD
     *
     * @mbggenerated
     */
    public BigDecimal getDoubleReward() {
        return doubleReward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZONE_MARK_ASSESSMENT.DOUBLE_REWARD
     *
     * @param doubleReward the value for ZONE_MARK_ASSESSMENT.DOUBLE_REWARD
     *
     * @mbggenerated
     */
    public void setDoubleReward(BigDecimal doubleReward) {
        this.doubleReward = doubleReward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZONE_MARK_ASSESSMENT.STATE_DATE
     *
     * @return the value of ZONE_MARK_ASSESSMENT.STATE_DATE
     *
     * @mbggenerated
     */
    public Date getStateDate() {
        return stateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZONE_MARK_ASSESSMENT.STATE_DATE
     *
     * @param stateDate the value for ZONE_MARK_ASSESSMENT.STATE_DATE
     *
     * @mbggenerated
     */
    public void setStateDate(Date stateDate) {
        this.stateDate = stateDate;
    }
}