package com.telecomjs.beans;

import java.math.BigDecimal;

public class ZoneMark {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZONE_MARK.MARK_ID
     *
     * @mbggenerated
     */
    private Long markId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZONE_MARK.ZONE_ID
     *
     * @mbggenerated
     */
    private Long zoneId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZONE_MARK.ITEM_ID
     *
     * @mbggenerated
     */
    private Long itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZONE_MARK.BILLING_CYCLE
     *
     * @mbggenerated
     */
    private Long billingCycle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZONE_MARK.VAL
     *
     * @mbggenerated
     */
    private BigDecimal val;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZONE_MARK.LAST_VAL
     *
     * @mbggenerated
     */
    private BigDecimal lastVal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZONE_MARK.MARK
     *
     * @mbggenerated
     */
    private BigDecimal mark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZONE_MARK.WEIGHT_MARK
     *
     * @mbggenerated
     */
    private BigDecimal weightMark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZONE_MARK.MARK_ID
     *
     * @return the value of ZONE_MARK.MARK_ID
     *
     * @mbggenerated
     */
    public Long getMarkId() {
        return markId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZONE_MARK.MARK_ID
     *
     * @param markId the value for ZONE_MARK.MARK_ID
     *
     * @mbggenerated
     */
    public void setMarkId(Long markId) {
        this.markId = markId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZONE_MARK.ZONE_ID
     *
     * @return the value of ZONE_MARK.ZONE_ID
     *
     * @mbggenerated
     */
    public Long getZoneId() {
        return zoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZONE_MARK.ZONE_ID
     *
     * @param zoneId the value for ZONE_MARK.ZONE_ID
     *
     * @mbggenerated
     */
    public void setZoneId(Long zoneId) {
        this.zoneId = zoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZONE_MARK.ITEM_ID
     *
     * @return the value of ZONE_MARK.ITEM_ID
     *
     * @mbggenerated
     */
    public Long getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZONE_MARK.ITEM_ID
     *
     * @param itemId the value for ZONE_MARK.ITEM_ID
     *
     * @mbggenerated
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZONE_MARK.BILLING_CYCLE
     *
     * @return the value of ZONE_MARK.BILLING_CYCLE
     *
     * @mbggenerated
     */
    public Long getBillingCycle() {
        return billingCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZONE_MARK.BILLING_CYCLE
     *
     * @param billingCycle the value for ZONE_MARK.BILLING_CYCLE
     *
     * @mbggenerated
     */
    public void setBillingCycle(Long billingCycle) {
        this.billingCycle = billingCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZONE_MARK.VAL
     *
     * @return the value of ZONE_MARK.VAL
     *
     * @mbggenerated
     */
    public BigDecimal getVal() {
        return val;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZONE_MARK.VAL
     *
     * @param val the value for ZONE_MARK.VAL
     *
     * @mbggenerated
     */
    public void setVal(BigDecimal val) {
        this.val = val;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZONE_MARK.LAST_VAL
     *
     * @return the value of ZONE_MARK.LAST_VAL
     *
     * @mbggenerated
     */
    public BigDecimal getLastVal() {
        return lastVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZONE_MARK.LAST_VAL
     *
     * @param lastVal the value for ZONE_MARK.LAST_VAL
     *
     * @mbggenerated
     */
    public void setLastVal(BigDecimal lastVal) {
        this.lastVal = lastVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZONE_MARK.MARK
     *
     * @return the value of ZONE_MARK.MARK
     *
     * @mbggenerated
     */
    public BigDecimal getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZONE_MARK.MARK
     *
     * @param mark the value for ZONE_MARK.MARK
     *
     * @mbggenerated
     */
    public void setMark(BigDecimal mark) {
        this.mark = mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZONE_MARK.WEIGHT_MARK
     *
     * @return the value of ZONE_MARK.WEIGHT_MARK
     *
     * @mbggenerated
     */
    public BigDecimal getWeightMark() {
        return weightMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZONE_MARK.WEIGHT_MARK
     *
     * @param weightMark the value for ZONE_MARK.WEIGHT_MARK
     *
     * @mbggenerated
     */
    public void setWeightMark(BigDecimal weightMark) {
        this.weightMark = weightMark;
    }
}