package com.telecomjs.beans;

import com.telecomjs.datagrid.DataColumn;

import java.util.Date;

public class ZoneKpiValue   {

    private String key;
    private Date startDate;

    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    public Date getStartDate() {
        return startDate;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZONE_KPI_VALUE.END_DATE
     *
     * @mbggenerated
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZONE_KPI_VALUE.VALUE
     *
     * @mbggenerated
     */
    private String value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZONE_KPI_VALUE.END_DATE
     *
     * @return the value of ZONE_KPI_VALUE.END_DATE
     *
     * @mbggenerated
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZONE_KPI_VALUE.END_DATE
     *
     * @param endDate the value for ZONE_KPI_VALUE.END_DATE
     *
     * @mbggenerated
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZONE_KPI_VALUE.VALUE
     *
     * @return the value of ZONE_KPI_VALUE.VALUE
     *
     * @mbggenerated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZONE_KPI_VALUE.VALUE
     *
     * @param value the value for ZONE_KPI_VALUE.VALUE
     *
     * @mbggenerated
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }
}