package com.telecomjs.beans;

import java.math.BigDecimal;

public class ZoneMarkItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZONE_MARK_ITEM.ITEM_ID
     *
     * @mbggenerated
     */
    private Long itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZONE_MARK_ITEM.RULE_ID
     *
     * @mbggenerated
     */
    private Short ruleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZONE_MARK_ITEM.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZONE_MARK_ITEM.DESCRIPTION
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZONE_MARK_ITEM.CODE
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZONE_MARK_ITEM.WEIGHT
     *
     * @mbggenerated
     */
    private BigDecimal weight;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZONE_MARK_ITEM.ITEM_ID
     *
     * @return the value of ZONE_MARK_ITEM.ITEM_ID
     *
     * @mbggenerated
     */
    public Long getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZONE_MARK_ITEM.ITEM_ID
     *
     * @param itemId the value for ZONE_MARK_ITEM.ITEM_ID
     *
     * @mbggenerated
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZONE_MARK_ITEM.RULE_ID
     *
     * @return the value of ZONE_MARK_ITEM.RULE_ID
     *
     * @mbggenerated
     */
    public Short getRuleId() {
        return ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZONE_MARK_ITEM.RULE_ID
     *
     * @param ruleId the value for ZONE_MARK_ITEM.RULE_ID
     *
     * @mbggenerated
     */
    public void setRuleId(Short ruleId) {
        this.ruleId = ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZONE_MARK_ITEM.NAME
     *
     * @return the value of ZONE_MARK_ITEM.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZONE_MARK_ITEM.NAME
     *
     * @param name the value for ZONE_MARK_ITEM.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZONE_MARK_ITEM.DESCRIPTION
     *
     * @return the value of ZONE_MARK_ITEM.DESCRIPTION
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZONE_MARK_ITEM.DESCRIPTION
     *
     * @param description the value for ZONE_MARK_ITEM.DESCRIPTION
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZONE_MARK_ITEM.CODE
     *
     * @return the value of ZONE_MARK_ITEM.CODE
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZONE_MARK_ITEM.CODE
     *
     * @param code the value for ZONE_MARK_ITEM.CODE
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZONE_MARK_ITEM.WEIGHT
     *
     * @return the value of ZONE_MARK_ITEM.WEIGHT
     *
     * @mbggenerated
     */
    public BigDecimal getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZONE_MARK_ITEM.WEIGHT
     *
     * @param weight the value for ZONE_MARK_ITEM.WEIGHT
     *
     * @mbggenerated
     */
    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }
}