package com.telecomjs.beans;

import java.math.BigDecimal;

public class ZoneMarkBase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZONE_MARK_BASE.MARK_ID
     *
     * @mbggenerated
     */
    private Long markId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZONE_MARK_BASE.ZONE_ID
     *
     * @mbggenerated
     */
    private Long zoneId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZONE_MARK_BASE.BILLING_CYCLE
     *
     * @mbggenerated
     */
    private Integer billingCycle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZONE_MARK_BASE.CHANNEL_TYPE
     *
     * @mbggenerated
     */
    private String channelType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZONE_MARK_BASE.DELEGATE_TYPE
     *
     * @mbggenerated
     */
    private String delegateType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZONE_MARK_BASE.CRITERION
     *
     * @mbggenerated
     */
    private BigDecimal criterion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZONE_MARK_BASE.MARK_ID
     *
     * @return the value of ZONE_MARK_BASE.MARK_ID
     *
     * @mbggenerated
     */
    public Long getMarkId() {
        return markId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZONE_MARK_BASE.MARK_ID
     *
     * @param markId the value for ZONE_MARK_BASE.MARK_ID
     *
     * @mbggenerated
     */
    public void setMarkId(Long markId) {
        this.markId = markId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZONE_MARK_BASE.ZONE_ID
     *
     * @return the value of ZONE_MARK_BASE.ZONE_ID
     *
     * @mbggenerated
     */
    public Long getZoneId() {
        return zoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZONE_MARK_BASE.ZONE_ID
     *
     * @param zoneId the value for ZONE_MARK_BASE.ZONE_ID
     *
     * @mbggenerated
     */
    public void setZoneId(Long zoneId) {
        this.zoneId = zoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZONE_MARK_BASE.BILLING_CYCLE
     *
     * @return the value of ZONE_MARK_BASE.BILLING_CYCLE
     *
     * @mbggenerated
     */
    public Integer getBillingCycle() {
        return billingCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZONE_MARK_BASE.BILLING_CYCLE
     *
     * @param billingCycle the value for ZONE_MARK_BASE.BILLING_CYCLE
     *
     * @mbggenerated
     */
    public void setBillingCycle(Integer billingCycle) {
        this.billingCycle = billingCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZONE_MARK_BASE.CHANNEL_TYPE
     *
     * @return the value of ZONE_MARK_BASE.CHANNEL_TYPE
     *
     * @mbggenerated
     */
    public String getChannelType() {
        return channelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZONE_MARK_BASE.CHANNEL_TYPE
     *
     * @param channelType the value for ZONE_MARK_BASE.CHANNEL_TYPE
     *
     * @mbggenerated
     */
    public void setChannelType(String channelType) {
        this.channelType = channelType == null ? null : channelType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZONE_MARK_BASE.DELEGATE_TYPE
     *
     * @return the value of ZONE_MARK_BASE.DELEGATE_TYPE
     *
     * @mbggenerated
     */
    public String getDelegateType() {
        return delegateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZONE_MARK_BASE.DELEGATE_TYPE
     *
     * @param delegateType the value for ZONE_MARK_BASE.DELEGATE_TYPE
     *
     * @mbggenerated
     */
    public void setDelegateType(String delegateType) {
        this.delegateType = delegateType == null ? null : delegateType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZONE_MARK_BASE.CRITERION
     *
     * @return the value of ZONE_MARK_BASE.CRITERION
     *
     * @mbggenerated
     */
    public BigDecimal getCriterion() {
        return criterion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZONE_MARK_BASE.CRITERION
     *
     * @param criterion the value for ZONE_MARK_BASE.CRITERION
     *
     * @mbggenerated
     */
    public void setCriterion(BigDecimal criterion) {
        this.criterion = criterion;
    }
}