package com.telecomjs.beans;

import java.util.Date;

public class ZoneMarkEvent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZONE_MARK_EVENT.EVENT_ID
     *
     * @mbggenerated
     */
    private Long eventId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZONE_MARK_EVENT.BILLING_CYCLE
     *
     * @mbggenerated
     */
    private Integer billingCycle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZONE_MARK_EVENT.CSS_NUMBER
     *
     * @mbggenerated
     */
    private Long cssNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZONE_MARK_EVENT.RECORD_NUMBERS
     *
     * @mbggenerated
     */
    private Long recordNumbers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZONE_MARK_EVENT.STATE_DATE
     *
     * @mbggenerated
     */
    private Date stateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZONE_MARK_EVENT.STATE
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZONE_MARK_EVENT.EVENT_ID
     *
     * @return the value of ZONE_MARK_EVENT.EVENT_ID
     *
     * @mbggenerated
     */
    public Long getEventId() {
        return eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZONE_MARK_EVENT.EVENT_ID
     *
     * @param eventId the value for ZONE_MARK_EVENT.EVENT_ID
     *
     * @mbggenerated
     */
    public void setEventId(Long eventId) {
        this.eventId = eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZONE_MARK_EVENT.BILLING_CYCLE
     *
     * @return the value of ZONE_MARK_EVENT.BILLING_CYCLE
     *
     * @mbggenerated
     */
    public Integer getBillingCycle() {
        return billingCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZONE_MARK_EVENT.BILLING_CYCLE
     *
     * @param billingCycle the value for ZONE_MARK_EVENT.BILLING_CYCLE
     *
     * @mbggenerated
     */
    public void setBillingCycle(Integer billingCycle) {
        this.billingCycle = billingCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZONE_MARK_EVENT.CSS_NUMBER
     *
     * @return the value of ZONE_MARK_EVENT.CSS_NUMBER
     *
     * @mbggenerated
     */
    public Long getCssNumber() {
        return cssNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZONE_MARK_EVENT.CSS_NUMBER
     *
     * @param cssNumber the value for ZONE_MARK_EVENT.CSS_NUMBER
     *
     * @mbggenerated
     */
    public void setCssNumber(Long cssNumber) {
        this.cssNumber = cssNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZONE_MARK_EVENT.RECORD_NUMBERS
     *
     * @return the value of ZONE_MARK_EVENT.RECORD_NUMBERS
     *
     * @mbggenerated
     */
    public Long getRecordNumbers() {
        return recordNumbers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZONE_MARK_EVENT.RECORD_NUMBERS
     *
     * @param recordNumbers the value for ZONE_MARK_EVENT.RECORD_NUMBERS
     *
     * @mbggenerated
     */
    public void setRecordNumbers(Long recordNumbers) {
        this.recordNumbers = recordNumbers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZONE_MARK_EVENT.STATE_DATE
     *
     * @return the value of ZONE_MARK_EVENT.STATE_DATE
     *
     * @mbggenerated
     */
    public Date getStateDate() {
        return stateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZONE_MARK_EVENT.STATE_DATE
     *
     * @param stateDate the value for ZONE_MARK_EVENT.STATE_DATE
     *
     * @mbggenerated
     */
    public void setStateDate(Date stateDate) {
        this.stateDate = stateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZONE_MARK_EVENT.STATE
     *
     * @return the value of ZONE_MARK_EVENT.STATE
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZONE_MARK_EVENT.STATE
     *
     * @param state the value for ZONE_MARK_EVENT.STATE
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }
}